[package]
name = "cwmp"
version = "0.1.0"
authors = ["jda"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = { git = "https://github.com/jdalberg/xml-rs", branch = "parsefix" }
log = "0.4.8"
chrono = "0.4.0"
quickcheck = "0.9"
quickcheck_macros = "0.9"
rand = "0.7.3"


[dev-dependencies]
doc-comment = "0.3"
