name: Coverage

on:
  schedule:
    - cron:  '0 2 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  
  coverage:
      runs-on: ubuntu-latest

      env:
        CARGO_INCREMENTAL: 0
        RUSTFLAGS: -Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort
        RUSTDOCFLAGS: -Cpanic=abort

      steps:
      - uses: actions/checkout@v2
      - name: Install grcov
        run: curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
      - name: Ensure nightly toolchain
        uses: actions-rs/toolchain@v1
        with:    
          toolchain: nightly

      - name: Build
        run: cargo +nightly build --verbose
      - name: Run tests
        run: cargo +nightly test --verbose
      - name: Coverage Zip
        run: zip -0 ccov.zip `find . \( -name "cwmp*.gc*" \) -print`
      - name: Coverage generate lcov.info
        run: ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-not-existing --excl-start "    fn shrink" --excl-stop "^    }" --ignore "/*" -o lcov.info
      - name: Coverage parse lcov.info
        run: bash <(curl -s https://codecov.io/bash) -f lcov.info -t b5f52310-db75-4eb7-aba3-d6726960a42c
        
