name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    
  coverage:
      runs-on: ubuntu-latest

      env:
        CARGO_INCREMENTAL: 0
        RUSTFLAGS: -Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort
        RUSTDOCFLAGS: -Cpanic=abort
        CODECOV_TOKEN: b5f52310-db75-4eb7-aba3-d6726960a42c

      steps:
      - uses: actions/checkout@v2
      - name: Install grcov
        run: curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
      - name: Build
        with:    
          toolchain: nightly
        run: cargo build --verbose
      - name: Run tests
        with:    
            toolchain: nightly
        run: cargo test --verbose
      - name: Coverage Zip
        with:    
              toolchain: nightly
        run: zip -0 ccov.zip `find . \( -name "cwmp*.gc*" \) -print`
      - name: Coverage generate lcov.info
        with:    
              toolchain: nightly
        run: ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info
      - name: Coverage parse lcov.info
        with:    
              toolchain: nightly
        run: bash <(curl -s https://codecov.io/bash) -f lcov.info
        
